React donate sample app
paypaldev/PayPal-React-Donate-Sample pull request #1
Opened 2022-11-30 21:26 UTC by prophen

2022-11-30 22:26 UTC, prophen commented
Demo
https://user-images.githubusercontent.com/3941856/204921527-073bb62e-46c0-4dcd-bcce-a323852a2a79.mov

2022-12-01 20:50 UTC, devpato requested changes

2022-12-01 20:50 UTC, devpato commented on src/DonateApp.jsx
> +}
I would put this DonateForm component in a separate file. So each component per file. I know they are tiny, but I believe it's easier to specify to the reader where things go and makes it more precise where to go and make any changes.

2022-12-01 20:50 UTC, devpato commented on src/DonateApp.jsx
> +
I would put this AmountPicker component in a separate file. So each component per file. I know they are tiny, but I believe it's easier to specify to the reader where things go and makes it more precise where to go and make any changes.

2022-12-01 20:50 UTC, devpato commented on src/DonateApp.jsx
> +  }
I don't think this function is necessary. I would just use the `setIsCustomSelected()` to set the state

2022-12-01 20:50 UTC, devpato commented on src/DonateApp.jsx
> +            onFocus={handleCustomNotSelected}
In this onFocus you can just do

```
onFocus={() => {
              setIsCustomSelected(false);
            }}
```

Similar to what you are doing on like 79 that way you don't need the `handleCustomNotSelected() `function and you keep your code consistent. Or is there a reason you decided to take this approach of creating a separate function to handle the **false** state?

2022-12-01 20:50 UTC, devpato commented on src/DonateApp.jsx
> +function DonateButton({ currency, amount }) {
I would put this DonateButton component in a separate file. So each component per file. I know they are tiny, but I believe it's easier to specify to the reader where things go and makes it more precise where to go and make any changes.

2022-12-01 20:50 UTC, devpato commented on src/DonateApp.jsx
> +      createOrder={(data, actions) => {
For clarity, I would put this in a separate function and call it how you did on line 149 with the `onApprove`.This also welcome you to keep your function isolated for more than just clarity but if in the future you want to add tests, you can test that specific function

2022-12-01 20:50 UTC, devpato commented on src/DonateApp.jsx
> +function DonationCardText({ children }) {
I would put this `DonationCardText` component in a separate file. So each component per file. I know they are tiny, but I believe it's easier to specify to the reader where things go and makes it more precise where to go and make any changes.

2022-12-01 20:50 UTC, devpato commented on src/DonateApp.jsx
> +export function DonateApp() {
I would put this DonateApp component in a separate file. So each component per file. I know they are tiny, but I believe it's easier to specify to the reader where things go and makes it more precise where to go and make any changes.

2022-12-01 20:50 UTC, devpato commented on src/DonateApp.jsx
> +function DonateButton({ currency, amount }) {
If I'm not mistaken you don't need to pass this prop of currency since anywhere in your code you are changing it and in the SDK options in your `DonateApp` component you are setting the default value as **USD**

2022-12-01 20:50 UTC, devpato commented on src/DonateApp.jsx
> +        <DonateButton currency="USD" amount={amount} />
Setting the currency here is not needed since you did in in the SDK options

2022-12-01 20:50 UTC, devpato commented on src/DonateApp.jsx
> +                    currency_code: currency,
you don't need this, more line 139

2022-12-01 20:56 UTC, prophen commented on src/DonateApp.jsx
> +}
That makes sense. The app that Jamund started for me was all in one file and I just took that one, changed the UI, and added a custom field.

2022-12-01 20:57 UTC, prophen commented on src/DonateApp.jsx
> +  }
I had it that way originally and I made the function because I tried adding more than on line to that function to do other things. I will take that out and  set the state inline

2022-12-01 21:03 UTC, prophen commented on src/DonateApp.jsx
> +function DonateButton({ currency, amount }) {
Thanks, @devpato. So to summarize your feedback: put the components in their own files, get rid of the unnecessary function and `currency` prop in `DonateButton`

I think all of that is reasonable. I'll make the changes for the next commit.

2022-12-01 21:05 UTC, prophen commented on src/DonateApp.jsx
> +                    currency_code: currency,
I think this was left over because we created a dropdown with different currencies for donation in an earlier version of the app. Thanks for looking it over thoroughly.

2022-12-01 21:07 UTC, prophen commented
> ### ❌ Deploy Preview for _pp-react-donations_ failed.
> Name	Link
> 🔨 Latest commit	[889f487](https://github.com/paypaldev/PayPal-React-Donate-Sample/commit/889f4879f5a705c52f86b02878e684fafe05b34a)
> 🔍 Latest deploy log	https://app.netlify.com/sites/pp-react-donations/deploys/638913553dece20009fdc609

I think this is failing because the auto deployment won't work. I can deploy from the CLI. It won't be an issue because this is just for development when the final app is ready, I'll use GitHub pages.

2022-12-01 21:12 UTC, prophen commented on src/DonateApp.jsx
> +  }, [amount]);
Yes, so that the button doesn't reload everytime the amount changes

2022-12-01 21:37 UTC, prophen commented on src/DonateApp.jsx
> +                    currency_code: currency,
I think for this setup we do. It will break without this. Could it be because we didn't use the `usePayPalScriptReducer`? Or maybe donations have extra requirements.

2022-12-15 21:05 UTC, devpato approved these changes

2022-12-15 21:06 UTC, devpato commented on src/DonateApp.jsx
> +                    currency_code: currency,
That's a very good question

2022-12-16 21:24 UTC, merged